PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,role TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS labs(
id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,location TEXT);
CREATE TABLE IF NOT EXISTS devices(
id INTEGER PRIMARY KEY AUTOINCREMENT,lab_id INTEGER NOT NULL,device_number TEXT NOT NULL,
device_type TEXT DEFAULT 'PC',specifications TEXT,status TEXT DEFAULT 'Working',
FOREIGN KEY(lab_id) REFERENCES labs(id));
CREATE TABLE IF NOT EXISTS tickets(
id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_no TEXT UNIQUE,user_id INTEGER NOT NULL,
device_id INTEGER,category TEXT NOT NULL,description TEXT NOT NULL,priority TEXT NOT NULL,
status TEXT DEFAULT 'Open',assigned_to INTEGER,image TEXT,resolution_note TEXT,
created_at TEXT DEFAULT CURRENT_TIMESTAMP,assigned_at TEXT,resolved_at TEXT,closed_at TEXT,
FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(device_id) REFERENCES devices(id),
FOREIGN KEY(assigned_to) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS ticket_history(
id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER,old_status TEXT,new_status TEXT,
changed_by INTEGER,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS feedback(
id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER UNIQUE,rating INTEGER,comment TEXT,
created_at TEXT DEFAULT CURRENT_TIMESTAMP);
